<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <PackageId>MailEngin</PackageId>
    <Version>0.1.0</Version>
    <Authors>MailEngin</Authors>
    <Company>MailEngin</Company>
    <Description>Official .NET SDK for the MailEngin Email API</Description>
    <PackageTags>mailengin;email;transactional-email;email-api</PackageTags>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/mailengin/mailengin-dotnet-sdk</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://mailengin.app</PackageProjectUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
    <None Include="../../README.md" Pack="true" PackagePath="/" />
    <None Include="../../LICENSE" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
